import = [
	"~/.config/alacritty/themes/dracula.toml"
]

[window]
dimensions = { columns = 80, lines = 28 } 

title = "Alacritty"
dynamic_title = false 

[font]
size= 12.0

normal = { family = "Hack", style = "Regular" }

bold = { family = "Hack", style = "Bold" }

italic = { family = "Hack", style = "Italic" }

bold_italic = { family = "Hack", style = "Bold Italic" }
